import {chromium,expect} from '@playwright/test';
import express from 'express';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import path from 'node:path';
import {spawn,spawnSync,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {Store} from '../../gateway/curation/store.js';
import {createCurationApp} from '../../gateway/curation/app.js';
mkdirSync('runtime',{recursive:true});
const root=mkdtempSync(path.resolve('runtime/curation-browser-'));
mkdirSync(path.join(root,'sources'));
const python=process.env.CURATION_PYTHON??path.resolve(process.platform==='win32'?'runtime/curation-venv/Scripts/python.exe':'runtime/curation-venv/bin/python');
const fixture=spawnSync(python,['tests/curation/fixture.py',path.join(root,'sources')],{encoding:'utf8',env:{...process.env,TEMP:root,TMP:root}});
if(fixture.status!==0)throw new Error(fixture.stderr);
mkdirSync('artifacts/curation',{recursive:true});
const store=new Store(path.join(root,'db'));
const app=createCurationApp(store,path.join(root,'sources'),'fixture-worker');
app.use(express.static(path.resolve('dist')));
app.get('/curation',(_q,r)=>r.sendFile(path.resolve('dist/index.html')));
const server=app.listen(0,'127.0.0.1');
await new Promise<void>(r=>server.once('listening',r));
const port=(server.address() as any).port;
const context=await chromium.launchPersistentContext(path.join(root,'browser'),{
 channel:'chrome',headless:true,viewport:{width:1440,height:1000},
 env:{...process.env,TEMP:root,TMP:root} as Record<string,string>});
const page=await context.newPage();
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
let worker:ChildProcess|undefined;
try{
 worker=spawn(python,['worker/curation.py'],{env:{...process.env,CURATION_API:'http://127.0.0.1:'+port,CURATION_WORKER_TOKEN:'fixture-worker',CURATION_SOURCE_ROOT:path.join(root,'sources'),CURATION_DATA_DIR:path.join(root,'db'),TEMP:root,TMP:root},stdio:'ignore'});
 for(const theme of ['light','dark'] as const){
 await page.emulateMedia({colorScheme:theme});
 await page.goto('http://127.0.0.1:'+port+'/curation');
 await expect(page.getByRole('heading',{name:'Library',exact:true})).toBeVisible();
 await expect(page.getByText('Start with a small, recorded task.')).toBeVisible();
 await page.screenshot({path:'artifacts/curation/library-'+theme+'.png',fullPage:true});
 }
 await page.getByRole('button',{name:'Collections',exact:true}).click();
 await page.getByLabel('Name',{exact:true}).fill('Browser fixture collection');
 await page.getByLabel('Intended use',{exact:true}).fill('Evaluation fixture; not training data');
 await page.getByRole('button',{name:'Create',exact:true}).click();
 await expect(page.getByRole('button',{name:/Browser fixture collection/})).toBeVisible();
 await page.reload();
 await page.getByRole('button',{name:'Collections',exact:true}).click();
 await expect(page.getByRole('button',{name:/Browser fixture collection/})).toBeVisible();
 await page.getByRole('button',{name:/Browser fixture collection/}).click();
 await expect(page.getByRole('button',{name:'Freeze immutable version'})).toBeDisabled();
 await page.getByRole('button',{name:'Register source',exact:true}).focus();
 await page.keyboard.press('Enter');
 await expect(page.getByRole('heading',{name:'Register a local BotFails snapshot'})).toBeVisible();
 await page.getByLabel('Name',{exact:true}).first().focus();
 if(await page.evaluate(()=>document.activeElement?.tagName)!=='INPUT')throw new Error('Keyboard focus failed');
 await page.screenshot({path:'artifacts/curation/source-form.png',fullPage:true});
 await page.getByLabel('Name',{exact:true}).first().fill('Explicit browser fixture');
 await page.getByLabel('Recording provenance').selectOption('fixture');
 await page.getByLabel('Snapshot folder, relative to source root').fill('snapshot');
 await page.getByLabel('Task folders, comma separated').fill('test/fixture');
 await page.getByLabel('Source license reference').fill('Synthetic fixture; no public dataset claim');
 await page.getByRole('button',{name:'Inspect selected files'}).click();
 await page.getByRole('button',{name:'Library',exact:true}).click();
 await expect(page.getByRole('button',{name:'Import this selection'})).toBeVisible({timeout:60000});
 await page.getByRole('button',{name:'Import this selection'}).click();
 await expect.poll(async()=>{const response=await context.request.get('http://127.0.0.1:'+port+'/api/v1/episodes');return (await response.json()).episodes.length;},{timeout:60000}).toBe(1);
 await page.getByRole('button',{name:'Search',exact:true}).click();
 await page.locator('.cu-link').click();
 await expect(page.getByRole('heading',{name:'Episode inspection'})).toBeVisible();
 await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.readyState),{timeout:30000}).toBeGreaterThanOrEqual(2);
 await page.getByText('Recorded state/action inspector',{exact:true}).click();
 await page.getByRole('button',{name:'Inspect recorded samples'}).click();
 await expect(page.getByLabel('Recorded row cursor')).toBeVisible({timeout:60000});
 await page.getByLabel('Recorded row cursor').focus();
 await page.keyboard.press('End');
 await expect(page.getByText(/Linked by the source row/)).toBeVisible();
 await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>Math.abs(v.currentTime-2/30))).toBeLessThan(.01);
 await page.getByLabel('Rationale',{exact:true}).fill('Synthetic fixture review; not a training-quality judgment.');
 await page.getByRole('button',{name:'Save review',exact:true}).click();
 await expect(page.getByText('Review saved. Earlier revisions remain available.')).toBeVisible();
 await page.getByText('Add this episode or interval to a collection',{exact:true}).click();
 await page.getByLabel('Selection scope').selectOption('interval');
 await page.getByLabel('First frame',{exact:true}).fill('1');
 await page.getByLabel('Last frame, exclusive').fill('3');
 await page.getByRole('button',{name:'Save selection',exact:true}).click();
 await expect(page.getByText(/Selection saved to Browser fixture collection/)).toBeVisible();
 await page.screenshot({path:'artifacts/curation/episode-inspection.png',fullPage:true});
 await page.getByRole('button',{name:'Collections',exact:true}).click();
 await page.getByRole('button',{name:/Browser fixture collection/}).click();
 await expect(page.getByRole('button',{name:'Freeze immutable version'})).toBeEnabled();
 await page.getByRole('button',{name:'Freeze immutable version'}).click();
 await expect(page.getByRole('button',{name:'Export selection',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Export selection',exact:true}).click();
 await page.locator('summary').filter({hasText:/^Jobs /}).click();
 await expect(page.getByRole('link',{name:'manifest.json',exact:true})).toBeVisible({timeout:60000});
 const href=await page.getByRole('link',{name:'manifest.json',exact:true}).getAttribute('href');
 const exported=await (await context.request.get('http://127.0.0.1:'+port+href)).json();
 if(exported.collection.members[0].interval.start!==1||exported.episodes[0].origin!=='fixture')throw new Error('Browser selection did not match exported manifest');
 await page.getByText('Settings',{exact:true}).click();
 await page.getByLabel('Theme',{exact:true}).selectOption('light');
 await page.reload();
 await expect(page.locator('html')).toHaveAttribute('data-curation-theme','light');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('Browser QA passed: themes, keyboard, real fixture import/playback, source-backed seeking, interval review/selection, immutable export and reload; no page errors.');
}finally{
 if(worker&&worker.exitCode===null){worker.kill();await once(worker,'exit');}
 await context.close();
 await new Promise<void>(r=>server.close(()=>r()));
 store.close();
 rmSync(root,{recursive:true,force:true});
}
